DataONEorg/hashstore

CONTRIBUTING.md
Switched from a static PNG to using Mermaid to generate a gitGraph, and had the graph match our release process. Also updated a few details of the release process, including branch naming, and added the idea of a `bugfix` branch. Closing #11
=> Correct gitflow graphic for contributing doc

src/hashstore/hashstore.py, tests/test_hashstore.py
Refactored store_sysmeta based on discussion with Arc Dev team - store_sysmeta now calls HashFSExt `put_sysmeta` which creates a temporary file with sysmeta content before atomically moving it to its permanent address.
=> Feature 17 refactor store sysmeta

README.md, src/hashstore/filehashstore/filehashstore.py, src/hashstore/hashstore.py, tests/conftest.py, tests/filehashstore/test_filehashstore.py, tests/filehashstore/test_filehashstore_interface.py
Public API method `store_sysmeta` has been refactored to `store_metadata`, along with the respective retrieve/delete methods, and all tests have been updated. 
**Notes:**
- Updated `hashstore` interface methods and descriptions
- Updated signature:
- `store_metadata(pid, metadata, format_id)`
- In Python, non-default argument cannot come before a default one (ex. `store_metadata(self, pid, format_id=None, metadata)`)
- When no `format_id` is supplied, we will use the default value in `hashstore.yaml`
- Successful calling of `store_sysmeta` will return the metadata_cid, which is the sha256 hex digest of the `pid + format_id`
- Documentation/comments have all been updated to distinguish between `object_cid` and `metadata_cid`
=> Feature-35: Refactor 'store_sysmeta' to 'store_metadata'

src/hashstore/filehashstore/filehashstore.py, src/hashstore/hashstore.py, tests/filehashstore/test_filehashstore.py, tests/filehashstore/test_filehashstore_interface.py
- Refactored `store_metadata()` to only store supplied metadata content (no more header)
- Refactored `retrieve_metadata()` to return a stream of the metadata content rather than a string
- Updated `store_metadata()`, `retrieve_metadata()` and `delete_metadata()` to use Hashstore's default metadata namespace/format_id when `format_id` is not supplied.
- Update `hashstore.py` interface doc strings
=> Feature-38: Metadata Public API Methods Refactor

.vscode/settings.json, src/hashstore/filehashstore/filehashstore.py, src/hashstore/hashstore.py
The bug raised in the original issue was not actually a bug, but a misunderstanding during my local testing with datasets. While reviewing this issue, I decided to refactor and clean up HashStore.
- Refactored `FileHashStore` codebase to improve code readability
- Extracted implementation details into their own methods
- Cleaned up comments and logging
- Ensured consistent usage of logging
- Fixed bug during the initialization process to verify HashStore where an exception will be thrown if we attempt to iterate over a directory that doesn't exist
=> Bugfix-43: Empty Directories

src/hashstore/filehashstore/filehashstore.py, tests/conftest.py, tests/filehashstore/test_filehashstore.py, tests/test_hashstore.py
- `FileHashStore` checks that a given store algorithm is part of the default list before writing `hashstore.yaml` config file
- Store algorithm value to be written in `hashstore.yaml` now gets standardized to the DataONE controlled algorithms for cross-language compatibility
=> Bugfix-42: Store Algorithm

src/hashstore/filehashstore/filehashstore.py, tests/conftest.py, tests/filehashstore/test_filehashstore.py, tests/test_hashstore.py
- HashStore now requires a DataONE controlled algorithm value to initialize
- Added new pytests
- Confirmed `--run-slow` tests successfully executed
=> Bugfix-50: Standardize HashStore Initialization Store Algorithm

src/hashstore/__init__.py, src/hashstore/filehashstore.py, src/hashstore/hashstore.py, tests/conftest.py, tests/test_filehashstore.py, tests/test_filehashstore_interface.py, tests/test_hashstore.py
Summary of Changs:
- Rename `HashAddress` to `ObjectMetadata`
- Remove relative path and absolute path attributes from `ObjectMetadata` and added new attribute `obj_size`
- Update `HashStore` interface method `store_object()` doc strings for new signature value `expected_object_size`
- Refactor `store_object()` and related methods to accommodate new value, add logic to validate the `expected_object_size` against the file size calculated, and add/update pytests.
=> Feature-46: Refactor HashAddress (ObjectMetadata)

src/hashstore/client.py
Summary:
- Removed code that limited the SQL results based on the size of the origin folder to convert into HashStore
- Methods now take the `-nobj` options value directly which dictates the size of results to review when forming the list to work with when storing, retrieving or deleting
=> Bugfix-58: Remove Unintended Limiter on SQL Results from Knbvm

src/hashstore/filehashstore.py, tests/test_filehashstore_interface.py
- Added termination code via `atexit` library to clean up tmp files if they still exist when the python interpreter is exiting
- Refactored `_mktmpfile` method to remove tmp file if it is interrupted unexpectedly or if user forces a termination.
- New pytest to test termination code
=> Feature-64: Store Object Cleanup

src/hashstore/client.py, src/hashstore/filehashstore.py, src/hashstore/hashstore.py
Refactored python docstrings to follow reStructuredText for sphinx-autodocumentation
=> Feature-70: Sphinx Autodocs

src/hashstore/filehashstore.py, tests/test_filehashstore_references.py
`tag_object` now creates a pid reference file when a cid reference file exists and is updated (a cid reference file can contain multiple pids)
=> Bug-75: Missing Pid Reference Files

src/hashstore/filehashstore.py, tests/test_filehashstore_references.py
If an object is determined to be invalid (verify_object process), the object will now be deleted to simplify the process. Previously, it only threw the relevant exception for the cause of the object being invalid.
=> Feature-76: Verify Object Refactor

README.md, src/hashstore/filehashstore.py, src/hashstore/hashstore.py, src/hashstore/hashstoreclient.py, tests/test_filehashstore.py, tests/test_filehashstore_interface.py, tests/test_filehashstore_references.py, tests/test_hashstore.py, tests/test_hashstore_client.py
This branch includes improvements and changes to FileHashStore based on the feedback received during code review with Jing and Matthew.
=> Feature-85: Code Review Optimizations

src/hashstore/filehashstore.py, tests/test_filehashstore_interface.py
When an object fails to store a series of exceptions are logged which are redundant/repetitive (too much info).
- Logging levels have been adjusted for the entire `store_object` process and related methods so that only one exception is thrown with the relevant stack trace/errors.
- Exception messaging has been revised to improve clarity
- New custom exception "PidObjectMetadataError"
=> Feature-90: `store_object` Exceptions & Logging

src/hashstore/filehashstore.py
Added more logging statements to help with debugging process.
=> Feature-93: Additional Logging Statements

src/hashstore/filehashstore.py, src/hashstore/hashstoreclient.py, tests/test_filehashstore_interface.py, tests/test_filehashstore_references.py
- Revised tagging synchronization process to use threading/multiprocessing library conditions in `tag_object` & new pytest to check fixes
- Add new custom exception `PidAlreadyExistsError` for improved clarity
=> BugFix-97: `tag_object` cid refs file missing pids

src/hashstore/filehashstore.py, tests/test_filehashstore_interface.py
- Revised 'tag_object' to create the necessary refs files (`pid` or `cid`) when they are needed & added new pytest
=> BugFix-101: `cid refs file` does not get cleaned up

src/hashstore/filehashstore.py, src/hashstore/filehashstore_exceptions.py, src/hashstore/hashstore.py, src/hashstore/hashstoreclient.py, tests/test_filehashstore.py, tests/test_filehashstore_interface.py, tests/test_filehashstore_references.py
- `verify_object` now throws custom exceptions (more descriptive)
- If called to verify an object with a checksum algorithm that is not part of the default list, will attempt to calculate the new checksum and verify it
- Refactored custom exception classes into their own module
- Deleted redundant code and cleaned up codebase & tests
=> Feature-109: `verify_object` Update

README.md, src/hashstore/filehashstore.py, tests/conftest.py, tests/test_filehashstore.py, tests/test_filehashstore_interface.py, tests/test_hashstore.py, tests/test_hashstore_client.py
- `filehashstore` now throws exception during init process if the given path is missing the `hashstore.yaml` config file and `/objects`, `/metadata` or `/refs` exists. Other folders or files are allowed to exist at the supplied location
- Updated pytests and references to old placeholder sysmeta namespace value to new designated value
- Updated README.md
=> Feature-112: `FileHashStore` Init Process Update

src/hashstore/filehashstore.py, src/hashstore/hashstore.py, src/hashstore/hashstoreclient.py, tests/test_filehashstore_interface.py, tests/test_hashstore_client.py
- `find_object` now returns a dictionary with the following keys:
- cid
- cid_object_path
- cid_refs_path
- pid_refs_path
- sysmeta_path
- Revised code that calls `find_object`, including the `hashstoreclient`, `get_hex_digest` method and `delete_object` method
- Updates to `hashstore` interface & pytests
=> Feature-113: `find_object` Update

src/hashstore/filehashstore.py, src/hashstore/filehashstore_exceptions.py, tests/test_filehashstore_interface.py, tests/test_filehashstore_references.py
- When `tag_object` is called explicitly by the user or the `store_object` method, a custom exception `HashStoreRefsAlreadyExists` is thrown if the refs files already exist for the given `pid` and `cid`
=> Feature-114: `tag_object` Update for Existing HashStore Files

README.md, src/hashstore/filehashstore.py, src/hashstore/hashstoreclient.py
- Move declaration of threading and multiprocessing variables to the `__init__` method to avoid conflicts during module importation and ensure proper initialization.
=> Bug-119: `hashstore` Library Import Conflict

src/hashstore/__init__.py, src/hashstore/filehashstore.py, src/hashstore/hashstore.py, tests/test_filehashstore.py, tests/test_hashstore.py
- Simplified `ObjectMetadata` by refactoring it into a dataclass, and moved it into `filehashstore` module to be consistent with java library
- Updated docstrings and pytests
=> Feature-126: Refactor `ObjectMetadata` to be a dataclass

src/hashstore/filehashstore.py, tests/test_hashstore.py
- Revised method that validates properties to return a new properties object that has ensure `store_depth` and `store_width` are integers
- Added new pytest
=> Feature-125: Improve HashStore Init

README.md, pyproject.toml, src/hashstore/__init__.py, src/hashstore/filehashstore.py, tests/conftest.py, tests/filehashstore/test_filehashstore.py, tests/filehashstore/test_filehashstore_interface.py
- Reviewed and cleaned up docstrings + pytests and reorganized code, and fixed minor bugs
- Used poetry bump to update versioning, and bumped version number to 1.1.0
- Added missing version info to `__init__.py` in `src/hashstore`
- Added type hints to all method signatures
=> Feature-133: Code clean-up for Release Prep

src/hashstore/filehashstore.py
- Refactored the hashstore config `hashstore.yaml` content creation into two parts:
- Comments
- This is a string
- Key-Value Pairs
- These pairs are now generated through the `yaml (PyYAML)` library via `yaml.dump(...)`
- These two pieces are combined together afterwards 
- The final hashstore config `hashstore.yaml` content begins with the comments and the key-value pairs follow immediately after
=> Feature-138: Construct HashStore Config Yaml with Library

src/hashstore/filehashstore.py
- Refactored logging statements to use logger instance instead of the logging library itself
- Cleaned up logging statements in `filehashstore` module
- Fixed bugs relating to potential dead lock issues where synchronization code was not called within a try block
=> Feature-140: Logging Enhancement

README.md
- Updated `README.md` with DOI and citation information
=> Feature-108: Citation Update Part 2
